## 菜单栏
menu:
  - name: # 名称
    url: # 链接


## 评论
comment:
  enable: # 是否启用
  type: # waline | giscus

# Waline https://waline.js.org/
waline:
  serverURL:
  options: # 配置项参考：https://waline.js.org/reference/client/props.html

# Giscus https://giscus.app/zh-CN
giscus:
  repo:
  repoid:
  category:
  categoryid:
  mapping:
  term:
  reactionsenabled:
  emitmetadata:
  inputposition:
  loading:


## 搜索
search:
  enable: # 是否启用
  type: # algolia

# Docsearch https://docsearch.algolia.com/apply/
algolia:
  appId: 
  apiKey: 
  indexName: 


## 友链
friends:
  - name: # 名称
    avatar: # 头像
    link: # 站点地址
    desc: # 描述

## 社交链接
socialLink:
  - name: # 名称
    link: # 跳转链接


## Footer 页脚
footer:
  builtUpTime: # 建站时间 2020-05-20 13:14:00


## 主题色
primaryColor: '#10b981'